### ISSUE TITLE
Will not load env variables

### ISSUE THREAD

**Issue by artman-shane** [honeycombio/intro-to-o11y-nodejs#7]
If deploying on node, the requirement of the tracing.js prior to the index.js will result not loading the dotenv library and ultimately the environment variables until after starting the tracer.

**Versions**

**Steps to reproduce**

1.clone repo ./run

**Additional context**
Moved the require of dotenv to tracing.js since it runs first and problem was remedied for my test scenario.

**Comment by jessitron** [comment]
oh, thank you for this!!

**Comment by jessitron** [comment]
resolved

I moved the env-var-reading functionality to ./run
this seems more straightforward than the library.
